//! Graph-of-Thought (GoT) reasoning over the concept graph.
//!
//! Per `PROPOSAL.md` §11.1 ("multi-step reasoning") and `PHASES.md`
//! Phase 6, the substrate's reasoning plane explores a directed
//! graph of *thoughts* — hypotheses, evidence, conclusions,
//! questions, refinements — connected by typed edges (`Supports`,
//! `Contradicts`, `Refines`, `Derives`, `Aggregates`).
//!
//! The executor is intentionally synchronous and budget-bounded so
//! it can be unit-tested against deterministic fakes; the production
//! runtime wires expansion to an SLM call (or to graph traversal
//! when factual grounding is needed) behind the same trait.
//!
//! # Pipeline
//!
//! 1. [`GoTExecutor::plan`] — turn a [`GoTQuery`] into a
//!    [`GoTPlan`] (initial decomposition into a question root
//!    plus zero or more sub-questions).
//! 2. [`GoTExecutor::expand`] — generate child thoughts from a
//!    leaf via a pluggable [`Expander`].
//! 3. [`GoTExecutor::evaluate`] — score every root → leaf path,
//!    return the best [`GoTResult`].
//! 4. [`GoTExecutor::execute`] — full pipeline; the result is
//!    serialisable for the reasoning plane and may be persisted as
//!    a [`crate::workflow::WorkflowTrace`].

use std::collections::{HashMap, VecDeque};

use chrono::{DateTime, Utc};
use concept_graph::{ConceptGraph, NodeId, RelationType};
use evidence_store::ScopeId;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::planner::{QueryClass, RetrievalMode};
use crate::traversal::{
    GraphTraversal, TraversalBudget, TraversalDirection, TraversalQuery, TraversalResult,
};
use crate::workflow::{TraceRecorder, WorkflowMemory, WorkflowTrace};

/// Identifier for a [`ThoughtNode`] (UUID v4 newtype).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct ThoughtId(pub Uuid);

impl ThoughtId {
    /// Generate a fresh id.
    pub fn new_v4() -> Self {
        Self(Uuid::new_v4())
    }
}

impl std::fmt::Display for ThoughtId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}

/// Kind of reasoning step a [`ThoughtNode`] carries.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ThoughtType {
    /// "Maybe X is true" — still being verified.
    Hypothesis,
    /// Concrete factual support drawn from the substrate (e.g.
    /// from a graph traversal).
    Evidence,
    /// Final or interim answer — the search target.
    Conclusion,
    /// Sub-question generated by decomposition.
    Question,
    /// Tightened restatement of a parent hypothesis.
    Refinement,
}

/// Typed edge between two thoughts.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ThoughtEdge {
    /// Child reinforces parent (e.g. evidence supporting a hypothesis).
    Supports,
    /// Child contradicts parent.
    Contradicts,
    /// Child is a tighter restatement of parent.
    Refines,
    /// Child is logically derived from parent.
    Derives,
    /// Child aggregates several parents into a synthesis.
    Aggregates,
}

/// One reasoning step in a [`ThoughtGraph`].
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ThoughtNode {
    /// Stable id.
    pub id: ThoughtId,
    /// Free-form content of the thought.
    pub content: String,
    /// Reasoning kind.
    pub thought_type: ThoughtType,
    /// Confidence score in `[0.0, 1.0]`.
    pub confidence: f64,
    /// Parent thoughts this node was generated from. Empty for the
    /// root.
    pub parent_ids: Vec<ThoughtId>,
    /// Scope this thought lives in (for permission filtering).
    pub scope_id: ScopeId,
    /// Wall-clock creation time.
    pub created_at: DateTime<Utc>,
}

impl ThoughtNode {
    /// Construct a fresh thought.
    pub fn new(
        content: impl Into<String>,
        thought_type: ThoughtType,
        confidence: f64,
        scope_id: ScopeId,
    ) -> Self {
        Self {
            id: ThoughtId::new_v4(),
            content: content.into(),
            thought_type,
            confidence: confidence.clamp(0.0, 1.0),
            parent_ids: Vec::new(),
            scope_id,
            created_at: Utc::now(),
        }
    }

    /// Set this node's parents (used by the executor when adding
    /// children to the graph).
    pub fn with_parents(mut self, parents: Vec<ThoughtId>) -> Self {
        self.parent_ids = parents;
        self
    }
}

/// In-memory directed graph of [`ThoughtNode`]s.
///
/// Edges are typed via [`ThoughtEdge`]; outgoing/incoming adjacency
/// is indexed for `O(1)` neighbour lookup. The graph is acyclic by
/// construction — children always point at *existing* parents.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ThoughtGraph {
    nodes: HashMap<ThoughtId, ThoughtNode>,
    /// `parent -> [(child, edge)]`
    children: HashMap<ThoughtId, Vec<(ThoughtId, ThoughtEdge)>>,
    /// Insertion order — useful for deterministic iteration in tests.
    order: Vec<ThoughtId>,
    /// Root thought (the seed produced by [`GoTExecutor::plan`]).
    root: Option<ThoughtId>,
}

impl ThoughtGraph {
    /// Construct an empty graph.
    pub fn new() -> Self {
        Self::default()
    }

    /// Number of thoughts.
    pub fn len(&self) -> usize {
        self.nodes.len()
    }

    /// True iff no thoughts have been added.
    pub fn is_empty(&self) -> bool {
        self.nodes.is_empty()
    }

    /// Look up a thought by id.
    pub fn get(&self, id: ThoughtId) -> Option<&ThoughtNode> {
        self.nodes.get(&id)
    }

    /// Iterate every thought in insertion order.
    pub fn iter(&self) -> impl Iterator<Item = &ThoughtNode> {
        self.order.iter().filter_map(move |id| self.nodes.get(id))
    }

    /// Get the root id, if [`Self::set_root`] has been called.
    pub fn root(&self) -> Option<ThoughtId> {
        self.root
    }

    /// Children of `id` (as `(child, edge)` tuples).
    pub fn children_of(&self, id: ThoughtId) -> &[(ThoughtId, ThoughtEdge)] {
        self.children.get(&id).map_or(&[][..], Vec::as_slice)
    }

    /// Insert a thought into the graph. Returns the thought id.
    /// Idempotent — re-inserting the same id keeps the existing
    /// node and returns its id.
    pub fn add(&mut self, thought: ThoughtNode) -> ThoughtId {
        let id = thought.id;
        if !self.nodes.contains_key(&id) {
            self.order.push(id);
            self.children.entry(id).or_default();
            self.nodes.insert(id, thought);
        }
        id
    }

    /// Mark `id` as the graph root. Overwrites any previous root.
    pub fn set_root(&mut self, id: ThoughtId) {
        self.root = Some(id);
    }

    /// Insert `child` as a descendant of every id in
    /// `child.parent_ids` and connect them with `edge`. The child
    /// must declare at least one parent already present in the
    /// graph.
    ///
    /// # Errors
    ///
    /// Returns `Err` if `child.parent_ids` is empty or any
    /// parent id is missing.
    pub fn connect_child(
        &mut self,
        child: ThoughtNode,
        edge: ThoughtEdge,
    ) -> Result<ThoughtId, GoTError> {
        if child.parent_ids.is_empty() {
            return Err(GoTError::DanglingChild);
        }
        for parent in &child.parent_ids {
            if !self.nodes.contains_key(parent) {
                return Err(GoTError::ParentNotFound);
            }
        }
        let parents = child.parent_ids.clone();
        let id = self.add(child);
        for parent in parents {
            self.children.entry(parent).or_default().push((id, edge));
        }
        Ok(id)
    }
}

/// Reasoning strategy controlling how the executor expands the
/// thought graph.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GoTStrategy {
    /// Expand all current frontier nodes before going deeper.
    BreadthFirst,
    /// Expand the most recently added node first.
    DepthFirst,
    /// Expand the highest-confidence frontier node first.
    #[default]
    BestFirst,
    /// Alternate: a single BFS pass at every depth, but cap the
    /// number of branches kept after each layer (best-of-K).
    Iterative,
}

/// Errors raised by the GoT executor.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum GoTError {
    /// Attempted to connect a child without parents.
    #[error("child thought has no parents")]
    DanglingChild,
    /// A child's declared parent is not in the graph.
    #[error("parent thought is not in the graph")]
    ParentNotFound,
    /// `evaluate` was called before any thoughts were added.
    #[error("thought graph is empty")]
    EmptyGraph,
}

/// Input to the GoT pipeline.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GoTQuery {
    /// Free-form query text — what the user is asking.
    pub question: String,
    /// Scope the reasoning runs in.
    pub scope: ScopeId,
    /// Reasoning strategy.
    pub strategy: GoTStrategy,
    /// Maximum depth from the root.
    pub max_depth: usize,
    /// Maximum branches kept per node after expansion (the
    /// "Iterative" / "BestFirst" strategies prune to this width).
    pub max_branches: usize,
    /// Hard cap on total node count — once exceeded, expansion
    /// stops.
    pub max_nodes: usize,
}

impl GoTQuery {
    /// Sensible-default query with a `BestFirst` strategy and
    /// modest budgets.
    pub fn new(question: impl Into<String>, scope: ScopeId) -> Self {
        Self {
            question: question.into(),
            scope,
            strategy: GoTStrategy::default(),
            max_depth: 3,
            max_branches: 3,
            max_nodes: 32,
        }
    }

    /// Override the strategy.
    pub fn with_strategy(mut self, s: GoTStrategy) -> Self {
        self.strategy = s;
        self
    }

    /// Override the budgets.
    pub fn with_budget(mut self, max_depth: usize, max_branches: usize, max_nodes: usize) -> Self {
        self.max_depth = max_depth;
        self.max_branches = max_branches;
        self.max_nodes = max_nodes;
        self
    }
}

/// Result of [`GoTExecutor::plan`] — the seed of the reasoning
/// graph plus any decomposed sub-questions.
#[derive(Debug, Clone)]
pub struct GoTPlan {
    /// Root thought (a `Question` carrying the user's query).
    pub root: ThoughtId,
    /// Sub-question children, in priority order.
    pub sub_questions: Vec<ThoughtId>,
}

/// One root → leaf path through the thought graph, along with its
/// score.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScoredPath {
    /// Thoughts in the path (root first, leaf last).
    pub thoughts: Vec<ThoughtNode>,
    /// Aggregated score; higher is better.
    pub score: f64,
    /// True if the path ends at a [`ThoughtType::Conclusion`].
    pub ends_at_conclusion: bool,
}

/// Final output of the GoT pipeline.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GoTResult {
    /// Best path found.
    pub best_path: Vec<ThoughtNode>,
    /// Every root → leaf path, sorted by descending score.
    pub all_paths: Vec<ScoredPath>,
    /// Confidence of the best path in `[0.0, 1.0]`.
    pub confidence: f64,
    /// Reasoning trace — every thought in the graph in the order
    /// it was generated.
    pub reasoning_trace: Vec<ThoughtNode>,
    /// True if any budget tripped during expansion.
    pub budget_exhausted: bool,
}

/// Pluggable thought-expansion strategy.
///
/// Implementors return zero or more child thoughts for a given
/// frontier node. The executor handles graph wiring, depth /
/// branch / node accounting, and pruning.
pub trait Expander {
    /// Generate up to `limit` child thoughts for `parent`. The
    /// returned thoughts must already have `parent.id` in their
    /// `parent_ids` (the executor will not patch this).
    fn expand(
        &self,
        parent: &ThoughtNode,
        depth: usize,
        limit: usize,
    ) -> Vec<(ThoughtNode, ThoughtEdge)>;
}

/// Static expander backed by a simple lookup `parent_id → children`
/// — used by tests so expansion is fully deterministic.
#[derive(Debug, Clone, Default)]
pub struct StaticExpander {
    children: HashMap<ThoughtId, Vec<(ThoughtNode, ThoughtEdge)>>,
}

impl StaticExpander {
    /// New, empty expander.
    pub fn new() -> Self {
        Self::default()
    }

    /// Register children for `parent`.
    pub fn register(
        &mut self,
        parent: ThoughtId,
        children: Vec<(ThoughtNode, ThoughtEdge)>,
    ) -> &mut Self {
        self.children.insert(parent, children);
        self
    }
}

impl Expander for StaticExpander {
    fn expand(
        &self,
        parent: &ThoughtNode,
        _depth: usize,
        limit: usize,
    ) -> Vec<(ThoughtNode, ThoughtEdge)> {
        self.children
            .get(&parent.id)
            .cloned()
            .unwrap_or_default()
            .into_iter()
            .take(limit)
            .collect()
    }
}

/// Expander that grounds reasoning in the concept graph by running
/// a [`GraphTraversal`] from a seed [`NodeId`] and emitting one
/// `Evidence` thought per visited node. Used as one of the
/// expansion strategies — see `expand_via_graph_traversal`.
#[derive(Debug, Clone)]
pub struct GraphExpander<'a> {
    graph: &'a ConceptGraph,
    seed: NodeId,
    edge_types: Vec<RelationType>,
    scope: ScopeId,
    budget: TraversalBudget,
}

impl<'a> GraphExpander<'a> {
    /// Construct a graph-grounded expander for `scope`.
    pub fn new(graph: &'a ConceptGraph, seed: NodeId, scope: ScopeId) -> Self {
        Self {
            graph,
            seed,
            edge_types: Vec::new(),
            scope,
            budget: TraversalBudget::default(),
        }
    }

    /// Restrict to specific edge types.
    pub fn with_edge_types(mut self, types: Vec<RelationType>) -> Self {
        self.edge_types = types;
        self
    }

    /// Override the traversal budget.
    pub fn with_budget(mut self, budget: TraversalBudget) -> Self {
        self.budget = budget;
        self
    }

    /// Run the underlying traversal once.
    pub fn run(&self) -> TraversalResult {
        let traversal = GraphTraversal::new(self.graph).with_budget(self.budget);
        let mut query = TraversalQuery::explore(self.seed)
            .with_direction(TraversalDirection::Outgoing)
            .with_scopes(vec![self.scope]);
        if !self.edge_types.is_empty() {
            query = query.with_edge_types(self.edge_types.clone());
        }
        traversal.run(&query)
    }
}

impl Expander for GraphExpander<'_> {
    fn expand(
        &self,
        parent: &ThoughtNode,
        _depth: usize,
        limit: usize,
    ) -> Vec<(ThoughtNode, ThoughtEdge)> {
        let result = self.run();
        result
            .visited
            .iter()
            .filter(|id| **id != self.seed)
            .take(limit)
            .map(|node_id| {
                let label = self
                    .graph
                    .get_node(*node_id)
                    .map_or_else(|| node_id.to_string(), |n| n.label.clone());
                let confidence = (parent.confidence * 0.9).clamp(0.0, 1.0);
                let evidence = ThoughtNode::new(
                    format!("Concept-graph evidence: {label}"),
                    ThoughtType::Evidence,
                    confidence,
                    self.scope,
                )
                .with_parents(vec![parent.id]);
                (evidence, ThoughtEdge::Supports)
            })
            .collect()
    }
}

/// Default scoring function: average confidence times a depth
/// penalty (paths are not penalised much, but very long paths lose
/// 5% per hop). Conclusions get a +0.1 boost.
fn default_score(path: &[ThoughtNode]) -> f64 {
    if path.is_empty() {
        return 0.0;
    }
    let sum: f64 = path.iter().map(|t| t.confidence).sum();
    let mut score = sum / path.len() as f64;
    let depth_penalty = 0.95_f64.powi(path.len().saturating_sub(1) as i32);
    score *= depth_penalty;
    if matches!(
        path.last().map(|t| t.thought_type),
        Some(ThoughtType::Conclusion)
    ) {
        score = (score + 0.1).min(1.0);
    }
    score
}

/// Orchestrates the GoT pipeline.
#[derive(Debug, Default)]
pub struct GoTExecutor;

impl GoTExecutor {
    /// New executor.
    pub fn new() -> Self {
        Self
    }

    /// Decompose `query` into a root thought (the question) plus
    /// any obvious sub-questions parsed from the text. The default
    /// implementation creates the root only — production callers
    /// can pre-seed sub-questions via `plan_with_subquestions`.
    pub fn plan(&self, graph: &mut ThoughtGraph, query: &GoTQuery) -> GoTPlan {
        let root = ThoughtNode::new(
            query.question.clone(),
            ThoughtType::Question,
            1.0,
            query.scope,
        );
        let root_id = graph.add(root);
        graph.set_root(root_id);
        GoTPlan {
            root: root_id,
            sub_questions: Vec::new(),
        }
    }

    /// Same as [`Self::plan`] but seed `sub_questions` as
    /// `Question` children connected to the root via
    /// [`ThoughtEdge::Refines`].
    pub fn plan_with_subquestions(
        &self,
        graph: &mut ThoughtGraph,
        query: &GoTQuery,
        sub_questions: &[String],
    ) -> Result<GoTPlan, GoTError> {
        let plan = self.plan(graph, query);
        let mut sub_ids = Vec::with_capacity(sub_questions.len());
        for q in sub_questions {
            let child = ThoughtNode::new(q.clone(), ThoughtType::Question, 0.9, query.scope)
                .with_parents(vec![plan.root]);
            let id = graph.connect_child(child, ThoughtEdge::Refines)?;
            sub_ids.push(id);
        }
        Ok(GoTPlan {
            root: plan.root,
            sub_questions: sub_ids,
        })
    }

    /// Generate child thoughts for `parent` using `expander`.
    pub fn expand<E: Expander>(
        &self,
        parent: &ThoughtNode,
        depth: usize,
        limit: usize,
        expander: &E,
    ) -> Vec<(ThoughtNode, ThoughtEdge)> {
        expander.expand(parent, depth, limit)
    }

    /// Run the full pipeline: plan, repeatedly expand under
    /// `query`'s strategy and budgets, then evaluate.
    ///
    /// This convenience entry point creates a fresh
    /// [`ThoughtGraph`] internally — convenient for ad-hoc
    /// reasoning, but unusable with a [`StaticExpander`] (or any
    /// other expander whose children reference pre-existing
    /// [`ThoughtId`]s) because the caller can never see those
    /// ids in advance. For that workflow build the graph and the
    /// [`GoTPlan`] yourself, register expansions against the now
    /// known root id, then call [`Self::execute_from_plan`].
    pub fn execute<E: Expander>(
        &self,
        query: &GoTQuery,
        expander: &E,
    ) -> Result<(ThoughtGraph, GoTResult), GoTError> {
        let mut graph = ThoughtGraph::new();
        let plan = self.plan(&mut graph, query);
        let budget_exhausted = self.expand_all(&mut graph, &plan, query, expander);
        let mut result = self.evaluate(&graph)?;
        result.budget_exhausted = budget_exhausted;
        Ok((graph, result))
    }

    /// Run the expand → evaluate pipeline against a graph and plan
    /// the caller already constructed. Use this when expansion is
    /// driven by something whose children must reference
    /// pre-existing [`ThoughtId`]s, e.g. [`StaticExpander`]: the
    /// caller wires up `expander` to the root and sub-question ids
    /// returned by [`Self::plan`] / [`Self::plan_with_subquestions`]
    /// before calling here, which is impossible if `execute`
    /// constructs the graph internally.
    pub fn execute_from_plan<E: Expander>(
        &self,
        graph: &mut ThoughtGraph,
        plan: &GoTPlan,
        query: &GoTQuery,
        expander: &E,
    ) -> Result<GoTResult, GoTError> {
        let budget_exhausted = self.expand_all(graph, plan, query, expander);
        let mut result = self.evaluate(graph)?;
        result.budget_exhausted = budget_exhausted;
        Ok(result)
    }

    /// Run an expansion pass on `graph` rooted at `plan` under
    /// `query`'s strategy and budgets. Returns `true` iff a
    /// budget tripped (i.e. `max_nodes` was exceeded). Public so
    /// tests and callers can pre-seed the graph and plan before
    /// invoking expansion.
    pub fn expand_all<E: Expander>(
        &self,
        graph: &mut ThoughtGraph,
        plan: &GoTPlan,
        query: &GoTQuery,
        expander: &E,
    ) -> bool {
        Self::run_expansion(graph, plan, query, expander)
    }

    /// Evaluate `graph`: enumerate every root → leaf path, score
    /// each one, and return the best.
    pub fn evaluate(&self, graph: &ThoughtGraph) -> Result<GoTResult, GoTError> {
        if graph.is_empty() {
            return Err(GoTError::EmptyGraph);
        }
        let root = graph.root().unwrap_or_else(|| {
            graph
                .order
                .first()
                .copied()
                .expect("non-empty graph has at least one node")
        });
        let mut paths: Vec<ScoredPath> = Vec::new();
        Self::collect_paths(graph, root, &mut Vec::new(), &mut paths);
        for path in &mut paths {
            path.score = default_score(&path.thoughts);
            path.ends_at_conclusion = path
                .thoughts
                .last()
                .is_some_and(|t| matches!(t.thought_type, ThoughtType::Conclusion));
        }
        paths.sort_by(|a, b| {
            b.score
                .partial_cmp(&a.score)
                .unwrap_or(std::cmp::Ordering::Equal)
        });
        let (best_path, confidence) = paths
            .first()
            .map_or_else(|| (Vec::new(), 0.0), |p| (p.thoughts.clone(), p.score));
        let trace: Vec<ThoughtNode> = graph.iter().cloned().collect();
        Ok(GoTResult {
            best_path,
            all_paths: paths,
            confidence,
            reasoning_trace: trace,
            budget_exhausted: false,
        })
    }

    /// Record the reasoning trace into [`WorkflowMemory`] as a
    /// [`WorkflowTrace`]. Returns the new trace id.
    pub fn record_trace(
        &self,
        memory: &mut WorkflowMemory,
        query: &GoTQuery,
        result: &GoTResult,
    ) -> Uuid {
        let mut recorder =
            TraceRecorder::begin(query.question.clone(), QueryClass::Holistic, query.scope);
        let succeeded = result
            .best_path
            .last()
            .is_some_and(|t| matches!(t.thought_type, ThoughtType::Conclusion));
        recorder.record_step(
            RetrievalMode::GraphTraversal,
            succeeded,
            0,
            Some(format!(
                "GoT: {} thoughts, {} paths",
                result.reasoning_trace.len(),
                result.all_paths.len()
            )),
        );
        let trace: WorkflowTrace = recorder.finish();
        memory.record(trace)
    }

    fn run_expansion<E: Expander>(
        graph: &mut ThoughtGraph,
        plan: &GoTPlan,
        query: &GoTQuery,
        expander: &E,
    ) -> bool {
        let mut frontier: VecDeque<(ThoughtId, usize)> = VecDeque::new();
        frontier.push_back((plan.root, 0));
        for sub in &plan.sub_questions {
            frontier.push_back((*sub, 1));
        }
        while let Some((node_id, depth)) = Self::pop_next(query.strategy, &mut frontier, graph) {
            if depth >= query.max_depth {
                continue;
            }
            if graph.len() >= query.max_nodes {
                return true;
            }
            let parent = match graph.get(node_id) {
                Some(p) => p.clone(),
                None => continue,
            };
            let children = expander.expand(&parent, depth, query.max_branches);
            let mut kept = 0;
            for (child, edge) in children {
                if kept >= query.max_branches {
                    break;
                }
                if graph.len() >= query.max_nodes {
                    return true;
                }
                let child = if child.parent_ids.is_empty() {
                    child.with_parents(vec![node_id])
                } else {
                    child
                };
                let Ok(id) = graph.connect_child(child, edge) else {
                    continue;
                };
                frontier.push_back((id, depth + 1));
                kept += 1;
            }
        }
        false
    }

    fn pop_next(
        strategy: GoTStrategy,
        frontier: &mut VecDeque<(ThoughtId, usize)>,
        graph: &ThoughtGraph,
    ) -> Option<(ThoughtId, usize)> {
        match strategy {
            GoTStrategy::BreadthFirst | GoTStrategy::Iterative => frontier.pop_front(),
            GoTStrategy::DepthFirst => frontier.pop_back(),
            GoTStrategy::BestFirst => {
                if frontier.is_empty() {
                    return None;
                }
                let mut best_idx = 0;
                let mut best_conf = f64::NEG_INFINITY;
                for (i, (id, _)) in frontier.iter().enumerate() {
                    if let Some(node) = graph.get(*id) {
                        if node.confidence > best_conf {
                            best_conf = node.confidence;
                            best_idx = i;
                        }
                    }
                }
                frontier.remove(best_idx)
            }
        }
    }

    fn collect_paths(
        graph: &ThoughtGraph,
        node_id: ThoughtId,
        current: &mut Vec<ThoughtNode>,
        out: &mut Vec<ScoredPath>,
    ) {
        let node = match graph.get(node_id) {
            Some(n) => n.clone(),
            None => return,
        };
        current.push(node);
        let kids = graph.children_of(node_id);
        if kids.is_empty() {
            out.push(ScoredPath {
                thoughts: current.clone(),
                score: 0.0,
                ends_at_conclusion: false,
            });
        } else {
            for (child_id, _) in kids {
                Self::collect_paths(graph, *child_id, current, out);
            }
        }
        current.pop();
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use concept_graph::{ConceptEdge, ConceptNode};

    fn scope() -> ScopeId {
        ScopeId::new_v4()
    }

    fn evidence(content: &str, conf: f64, parent: ThoughtId, s: ScopeId) -> ThoughtNode {
        ThoughtNode::new(content, ThoughtType::Evidence, conf, s).with_parents(vec![parent])
    }

    fn conclusion(content: &str, conf: f64, parent: ThoughtId, s: ScopeId) -> ThoughtNode {
        ThoughtNode::new(content, ThoughtType::Conclusion, conf, s).with_parents(vec![parent])
    }

    fn run(
        exec: &GoTExecutor,
        graph: &mut ThoughtGraph,
        plan: &GoTPlan,
        query: &GoTQuery,
        expander: &StaticExpander,
    ) -> GoTResult {
        let exhausted = exec.expand_all(graph, plan, query, expander);
        let mut result = exec.evaluate(graph).expect("evaluate");
        result.budget_exhausted = exhausted;
        result
    }

    #[test]
    fn single_hop_reasoning_runs_to_completion() {
        let s = scope();
        let q = GoTQuery::new("Why did Atlas slip?", s).with_budget(2, 2, 16);
        let mut graph = ThoughtGraph::new();
        let exec = GoTExecutor::new();
        let plan = exec.plan(&mut graph, &q);
        let mut expander = StaticExpander::new();
        expander.register(
            plan.root,
            vec![(
                conclusion(
                    "Spec slipped because of dependency on KMS",
                    0.9,
                    plan.root,
                    s,
                ),
                ThoughtEdge::Derives,
            )],
        );
        let result = run(&exec, &mut graph, &plan, &q, &expander);
        assert!(!result.best_path.is_empty());
        assert!(result.confidence > 0.0);
        assert!(matches!(
            result.best_path.last().unwrap().thought_type,
            ThoughtType::Conclusion
        ));
    }

    #[test]
    fn multi_branch_explores_and_picks_best() {
        let s = scope();
        let q = GoTQuery::new("Why does the bench run hot?", s)
            .with_budget(3, 3, 32)
            .with_strategy(GoTStrategy::BestFirst);
        let mut graph = ThoughtGraph::new();
        let exec = GoTExecutor::new();
        let plan = exec.plan(&mut graph, &q);
        let mut expander = StaticExpander::new();
        let h1 = ThoughtNode::new("Disk thrash", ThoughtType::Hypothesis, 0.4, s)
            .with_parents(vec![plan.root]);
        let h2 = ThoughtNode::new("CPU pinned", ThoughtType::Hypothesis, 0.85, s)
            .with_parents(vec![plan.root]);
        let h1_id = h1.id;
        let h2_id = h2.id;
        expander.register(
            plan.root,
            vec![(h1, ThoughtEdge::Supports), (h2, ThoughtEdge::Supports)],
        );
        expander.register(
            h1_id,
            vec![(
                evidence("iostat shows idle", 0.3, h1_id, s),
                ThoughtEdge::Contradicts,
            )],
        );
        expander.register(
            h2_id,
            vec![(
                conclusion("Pin to fewer cores", 0.95, h2_id, s),
                ThoughtEdge::Derives,
            )],
        );
        let result = run(&exec, &mut graph, &plan, &q, &expander);
        // Best path should run through the high-confidence hypothesis.
        assert!(result
            .best_path
            .iter()
            .any(|t| t.content.contains("CPU pinned")));
        assert!(result
            .best_path
            .iter()
            .any(|t| matches!(t.thought_type, ThoughtType::Conclusion)));
        assert!(graph.len() >= 4, "graph should contain at least 4 thoughts");
    }

    #[test]
    fn max_depth_caps_expansion() {
        let s = scope();
        let q = GoTQuery::new("chain", s).with_budget(2, 1, 100);
        let mut graph = ThoughtGraph::new();
        let exec = GoTExecutor::new();
        let plan = exec.plan(&mut graph, &q);
        // Build a 5-deep chain via the expander; only depth 2 should
        // be reached from root.
        let mut expander = StaticExpander::new();
        let mut prev = plan.root;
        let mut step_ids = Vec::new();
        for i in 0..5 {
            let n = ThoughtNode::new(format!("step-{i}"), ThoughtType::Hypothesis, 0.8, s)
                .with_parents(vec![prev]);
            let id = n.id;
            expander.register(prev, vec![(n, ThoughtEdge::Derives)]);
            step_ids.push(id);
            prev = id;
        }
        let _result = run(&exec, &mut graph, &plan, &q, &expander);
        // Root + 2 expansions = at most 3 thoughts in the chain.
        assert!(graph.len() <= 3);
    }

    #[test]
    fn max_nodes_short_circuits_and_flags_budget() {
        let s = scope();
        let q = GoTQuery::new("fan out", s).with_budget(5, 5, 3);
        let mut graph = ThoughtGraph::new();
        let exec = GoTExecutor::new();
        let plan = exec.plan(&mut graph, &q);
        let mut expander = StaticExpander::new();
        let kids: Vec<_> = (0..10)
            .map(|i| {
                (
                    ThoughtNode::new(format!("kid-{i}"), ThoughtType::Hypothesis, 0.5, s)
                        .with_parents(vec![plan.root]),
                    ThoughtEdge::Supports,
                )
            })
            .collect();
        expander.register(plan.root, kids);
        let result = run(&exec, &mut graph, &plan, &q, &expander);
        assert!(graph.len() <= q.max_nodes);
        assert!(result.budget_exhausted, "max_nodes trips budget flag");
    }

    #[test]
    fn breadth_first_and_depth_first_return_same_paths() {
        let s = scope();
        let mut graph_bfs = ThoughtGraph::new();
        let mut graph_dfs = ThoughtGraph::new();
        let exec = GoTExecutor::new();
        let q_bfs = GoTQuery::new("compare", s)
            .with_budget(2, 2, 16)
            .with_strategy(GoTStrategy::BreadthFirst);
        let q_dfs = q_bfs.clone().with_strategy(GoTStrategy::DepthFirst);
        let plan_bfs = exec.plan(&mut graph_bfs, &q_bfs);
        let plan_dfs = exec.plan(&mut graph_dfs, &q_dfs);
        // Use the same shape of expansion for both.
        let mut bfs_expander = StaticExpander::new();
        let mut dfs_expander = StaticExpander::new();
        let leaf_a_bfs = conclusion("a", 0.9, plan_bfs.root, s);
        let leaf_a_dfs = conclusion("a", 0.9, plan_dfs.root, s);
        bfs_expander.register(plan_bfs.root, vec![(leaf_a_bfs, ThoughtEdge::Derives)]);
        dfs_expander.register(plan_dfs.root, vec![(leaf_a_dfs, ThoughtEdge::Derives)]);
        let r1 = run(&exec, &mut graph_bfs, &plan_bfs, &q_bfs, &bfs_expander);
        let r2 = run(&exec, &mut graph_dfs, &plan_dfs, &q_dfs, &dfs_expander);
        assert_eq!(r1.best_path.len(), r2.best_path.len());
    }

    #[test]
    fn graph_expander_grounds_in_concept_graph() {
        let s = scope();
        let mut cg = ConceptGraph::new();
        let a = cg
            .add_node(ConceptNode::new_candidate("Atlas", "project", s))
            .unwrap();
        let b = cg
            .add_node(ConceptNode::new_candidate("KMS", "service", s))
            .unwrap();
        cg.add_edge(ConceptEdge::new(a, b, RelationType::PartOf, s))
            .unwrap();
        let parent = ThoughtNode::new("seed", ThoughtType::Question, 0.9, s);
        let parent_id = parent.id;
        let mut graph = ThoughtGraph::new();
        graph.add(parent);
        let exp = GraphExpander::new(&cg, a, s);
        let kids = exp.expand(graph.get(parent_id).unwrap(), 0, 4);
        assert!(
            !kids.is_empty(),
            "graph expander returns at least one evidence node",
        );
        for (child, edge) in &kids {
            assert!(matches!(child.thought_type, ThoughtType::Evidence));
            assert!(matches!(edge, ThoughtEdge::Supports));
        }
    }

    #[test]
    fn record_trace_persists_into_workflow_memory() {
        let s = scope();
        let q = GoTQuery::new("trace me", s);
        let exec = GoTExecutor::new();
        let mut expander = StaticExpander::new();
        let mut graph = ThoughtGraph::new();
        let plan = exec.plan(&mut graph, &q);
        expander.register(
            plan.root,
            vec![(
                conclusion("answer", 0.95, plan.root, s),
                ThoughtEdge::Derives,
            )],
        );
        let (_g, result) = exec.execute(&q, &expander).unwrap();
        let mut mem = WorkflowMemory::new();
        let id = exec.record_trace(&mut mem, &q, &result);
        assert!(mem.get_trace(id).is_ok());
    }

    #[test]
    fn evaluate_on_empty_graph_returns_error() {
        let exec = GoTExecutor::new();
        let graph = ThoughtGraph::new();
        let err = exec.evaluate(&graph).unwrap_err();
        assert_eq!(err, GoTError::EmptyGraph);
    }

    #[test]
    fn connect_child_rejects_dangling_and_missing_parent() {
        let s = scope();
        let mut graph = ThoughtGraph::new();
        let dangling = ThoughtNode::new("orphan", ThoughtType::Hypothesis, 0.5, s);
        let err = graph
            .connect_child(dangling, ThoughtEdge::Supports)
            .unwrap_err();
        assert_eq!(err, GoTError::DanglingChild);

        let stranger_id = ThoughtId::new_v4();
        let bad =
            ThoughtNode::new("x", ThoughtType::Hypothesis, 0.5, s).with_parents(vec![stranger_id]);
        let err = graph.connect_child(bad, ThoughtEdge::Supports).unwrap_err();
        assert_eq!(err, GoTError::ParentNotFound);
    }

    #[test]
    fn plan_with_subquestions_wires_children_to_root() {
        let s = scope();
        let q = GoTQuery::new("decompose", s);
        let exec = GoTExecutor::new();
        let mut graph = ThoughtGraph::new();
        let plan = exec
            .plan_with_subquestions(&mut graph, &q, &["a".into(), "b".into()])
            .unwrap();
        assert_eq!(plan.sub_questions.len(), 2);
        for sub in &plan.sub_questions {
            let node = graph.get(*sub).unwrap();
            assert_eq!(node.parent_ids, vec![plan.root]);
            assert!(matches!(node.thought_type, ThoughtType::Question));
        }
    }
}
