/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Drop the open evidence store. Mirrors [`crate::close_store`]. */
export declare function closeStore(handle: bigint): void

/**
 * Return the package version of the Rust core baked into this
 * `.node` artefact. Mirrors [`crate::core_version`]. Lets the JS-side
 * bootstrapper assert against a known-good version before opening
 * any stores so a stale addon from a previous install doesn't
 * silently corrupt data.
 */
export declare function coreVersion(): string

/**
 * Decrypt a base64-encoded ciphertext envelope. Mirrors
 * [`crate::decrypt`].
 */
export declare function decrypt(handle: bigint, scopeId: string, ciphertextB64: string): string

/**
 * Encrypt a base64-encoded plaintext for a scope. Mirrors
 * [`crate::encrypt`].
 */
export declare function encrypt(handle: bigint, scopeId: string, plaintextB64: string): string

/**
 * Escape a user-supplied FTS5 query. Mirrors
 * [`crate::escape_fts_query`].
 */
export declare function escapeFtsQuery(input: string): string

/** Force-archive a memory record. Mirrors [`crate::forget`]. */
export declare function forget(handle: bigint, id: string): void

/**
 * Destroy all key material for a scope. Mirrors
 * [`crate::forget_scope`].
 */
export declare function forgetScope(handle: bigint, scopeId: string): void

/**
 * Generate a fresh signing keypair. Mirrors
 * [`crate::generate_keypair`]. The returned object has `algorithm`,
 * `publicKey`, `privateKey` fields (the key fields are arrays of
 * byte integers in `[0, 255]`).
 */
export declare function generateKeypair(): any

/**
 * Fetch the channel-level synthesis memory. Mirrors
 * [`crate::get_channel_memory`].
 */
export declare function getChannelMemory(handle: bigint, scopeId: string): any

/** Fetch a single evidence row. Mirrors [`crate::get_evidence`]. */
export declare function getEvidence(handle: bigint, evidenceId: string): any

/**
 * Fetch the per-user memory bundle for a scope. Mirrors
 * [`crate::get_user_memory`].
 */
export declare function getUserMemory(handle: bigint, scopeId: string): any

/**
 * Full health envelope. Mirrors [`crate::health_check`].
 *
 * `handle` is optional:
 * * pass `0n` (or omit it via the TypeScript optional parameter)
 *   to get a bridge-only envelope — useful immediately after
 *   loading the addon, before any [`js_open_store`] call.
 * * pass a [`BigInt`] returned by [`js_open_store`] to get a full
 *   probe (`bridge` + `evidence_store` + `crypto` + `memory_manager`
 *   + `inference_router` subsystems, with real per-subsystem I/O).
 *
 * Returns the [`ffi::HealthStatus`] envelope serialised to JSON.
 * JS hosts get a typed object via napi's `serde_json::Value`
 * transparent passthrough; the shape is documented in
 * `crates/napi/index.d.ts`.
 */
export declare function healthCheck(handle?: bigint | undefined | null): any

/**
 * Ingest a chat / document message. Mirrors
 * [`crate::ingest_message`]. The `req` argument is a plain JS
 * object shaped like [`IngestRequest`].
 */
export declare function ingestMessage(handle: bigint, req: any): any

/** Initialise the Rust core. Mirrors [`crate::init`]. */
export declare function init(configJson: string): void

/**
 * List memory records, optionally filtered. Mirrors
 * [`crate::list_memories`]. The `filter` argument is a JSON object
 * whose key set must match [`MemoryFilter`] exactly — `state` is
 * optional (`null` or omitted ⇒ no state filter) and `pinned_only`
 * is a required bool. The struct carries
 * `#[serde(deny_unknown_fields)]`, so a typo like `pinnedOnly`
 * (camelCase) or `Pinned_Only` errors out with a clear
 * `InvalidArgument` rather than silently defaulting — this catches
 * JS-side mistakes at the FFI boundary instead of letting them
 * surface as missing memory rows later in the pipeline.
 */
export declare function listMemories(handle: bigint, scopeId: string, filter: any): any

/**
 * Open the SQLCipher-backed evidence store. Mirrors
 * [`crate::open_store`]. Returns a JS `BigInt` handle the caller
 * passes back into every subsequent call.
 */
export declare function openStore(path: string, masterKeyHex: string): bigint

/** Pin a memory record. Mirrors [`crate::pin`]. */
export declare function pin(handle: bigint, id: string): void

/** Hybrid query against a scope. Mirrors [`crate::query`]. */
export declare function query(handle: bigint, req: any): any

/**
 * Run the per-scope memory decay sweep. Mirrors
 * [`crate::run_decay_sweep`].
 */
export declare function runDecaySweep(handle: bigint, scopeId: string): number

/**
 * Trigger synthesis for a scope. Mirrors
 * [`crate::trigger_synthesis`]. `trigger` is one of
 * `"ManualUserAction"` / `"BackgroundIdle"` / `"EvidenceThreshold"` /
 * `"ConnectorSyncCompleted"` (matching the
 * [`SynthesisTrigger`] enum's serde-rename rules).
 */
export declare function triggerSynthesis(handle: bigint, scopeId: string, trigger: string): string

/** Lift a pin. Mirrors [`crate::unpin`]. */
export declare function unpin(handle: bigint, id: string): void
