/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Admit an approved document onto the tenant memory for `scopeId`
 * and persist its AEAD-encrypted payload alongside. Mirrors
 * [`crate::admit_approved_document`].
 *
 * `payload` is the raw plaintext document bytes; the substrate
 * seals it under the per-scope DEK before writing. The 16 MiB cap
 * is enforced inside the FFI layer — oversize payloads are
 * rejected with `Memory` and a message naming both the offending
 * size and the cap.
 *
 * Returns the serialised [`ffi::ApprovedDocumentSummary`] with
 * camelCase keys:
 * `{ id, scopeId, label, approver, approvedAtMs, payloadBytes,
 *    contentHashHex }`.
 *
 * # Errors
 *
 * * `NotFound` if the scope has no tenant memory object
 *   registered (or has been forgotten).
 * * `Memory` if `label` / `approver` / `payload` are empty or
 *   exceed their documented size caps.
 * * `InvalidArgument` if `scopeId` is not a UUID.
 */
export declare function admitApprovedDocument(handle: bigint, scopeId: string, label: string, approver: string, payload: Buffer): any

/**
 * Run the OAuth2 `authorization_code` exchange for an existing
 * connector instance. Mirrors [`crate::authenticate_connector`].
 */
export declare function authenticateConnector(handle: bigint, instanceId: string, authCode: string): void

/**
 * Unregister the previously-registered OAuth2 client-secret
 * resolver on `handle`. Mirrors
 * [`crate::clear_oauth_client_secret_resolver`].
 *
 * Calling this when no resolver is registered is a no-op.
 */
export declare function clearOauthClientSecretResolver(handle: bigint): void

/**
 * Remove the scheduler's per-instance policy override for
 * `instanceId` (Phase 6). The instance falls back to the
 * scheduler's defaults; the accounting state is cleared so a
 * long-Failing instance gets a fresh chance.
 *
 * Idempotent: clearing an instance with no override is `Ok(())`.
 *
 * # Errors
 *
 * * `Unavailable` if `open_store(handle)` has not yet been called.
 * * `Connector` if no scheduler is running on this handle.
 * * `InvalidArgument` if `instanceId` is not a UUID.
 */
export declare function clearSyncSchedule(handle: bigint, instanceId: string): void

/** Drop the open evidence store. Mirrors [`crate::close_store`]. */
export declare function closeStore(handle: bigint): void

/**
 * Toggle the post-sync auto-synthesis hook for a connector
 * instance (Phase 7). Mirrors [`crate::configure_sync_auto_synthesize`].
 *
 * When `enabled` is `true`, the scheduler dispatches a domain-tier
 * `triggerServerSynthesis` after every successful sync of this
 * instance, subject to the per-scope cooldown.
 *
 * # Errors
 *
 * * `Connector` if no scheduler is running on this handle.
 * * `InvalidArgument` if `instanceId` is not a UUID.
 */
export declare function configureSyncAutoSynthesize(handle: bigint, instanceId: string, enabled: boolean): void

/**
 * Override the scheduler's policy for a specific connector
 * instance (Phase 6). The override takes precedence over the
 * defaults supplied at [`js_start_sync_scheduler`] time.
 *
 * Idempotent: a second call replaces the prior policy. Also
 * resets the instance's `consecutive_failures` counter to zero —
 * the new policy starts from a clean slate.
 *
 * # Errors
 *
 * * `Unavailable` if `open_store(handle)` has not yet been called.
 * * `Connector` if no scheduler is running on this handle.
 * * `InvalidArgument` if `instanceId` is not a UUID,
 *   `syncIntervalSecs` is `0`, or
 *   `maxBackoffSecs < syncIntervalSecs`.
 */
export declare function configureSyncSchedule(handle: bigint, instanceId: string, syncIntervalSecs: number, maxBackoffSecs: number): void

/**
 * Install the server-side synthesis engine on the runtime.
 * Mirrors [`crate::configure_synthesis_engine`].
 *
 * `config` is the JSON object documented on
 * [`ffi::SynthesisEngineConfig`] with camelCase keys:
 * `{ url, apiKeyRef, modelId, maxTokens, timeoutMs, grammar,
 *    scopeBindings }`. `scopeBindings`, if present, is an array
 * of UUID strings the FFI layer admits for dispatch (production
 * deployments SHOULD configure it; an absent allow-list logs a
 * warning on every dispatch).
 *
 * # Errors
 *
 * * `Unavailable` if `openStore(handle)` has not been called or
 *   the build lacks the `http-client` feature.
 * * `InvalidArgument` if `config.url` is empty or any
 *   `scopeBindings` entry fails to parse as a UUID.
 */
export declare function configureSynthesisEngine(handle: bigint, config: any): void

/**
 * Return the package version of the Rust core baked into this
 * `.node` artefact. Mirrors [`crate::core_version`]. Lets the JS-side
 * bootstrapper assert against a known-good version before opening
 * any stores so a stale addon from a previous install doesn't
 * silently corrupt data.
 */
export declare function coreVersion(): string

/** Instantiate a connector. Mirrors [`crate::create_connector`]. */
export declare function createConnector(handle: bigint, kind: any, scopeId: string, configJson: string): string

/**
 * Decrypt a base64-encoded ciphertext envelope. Mirrors
 * [`crate::decrypt`].
 */
export declare function decrypt(handle: bigint, scopeId: string, ciphertextB64: string): string

/**
 * Encrypt a base64-encoded plaintext for a scope. Mirrors
 * [`crate::encrypt`].
 */
export declare function encrypt(handle: bigint, scopeId: string, plaintextB64: string): string

/**
 * Escape a user-supplied FTS5 query. Mirrors
 * [`crate::escape_fts_query`].
 */
export declare function escapeFtsQuery(input: string): string

/** Force-archive a memory record. Mirrors [`crate::forget`]. */
export declare function forget(handle: bigint, id: string): void

/**
 * Destroy all key material for a scope. Mirrors
 * [`crate::forget_scope`].
 */
export declare function forgetScope(handle: bigint, scopeId: string): void

/**
 * Generate a fresh signing keypair. Mirrors
 * [`crate::generate_keypair`]. The returned object has `algorithm`,
 * `publicKey`, `privateKey` fields (the key fields are arrays of
 * byte integers in `[0, 255]`).
 */
export declare function generateKeypair(): any

/**
 * Fetch the channel-level synthesis memory. Mirrors
 * [`crate::get_channel_memory`].
 */
export declare function getChannelMemory(handle: bigint, scopeId: string): any

/** Fetch a single evidence row. Mirrors [`crate::get_evidence`]. */
export declare function getEvidence(handle: bigint, evidenceId: string): any

/**
 * Fetch the per-user memory bundle for a scope. Mirrors
 * [`crate::get_user_memory`].
 */
export declare function getUserMemory(handle: bigint, scopeId: string): any

/**
 * Full health envelope. Mirrors [`crate::health_check`].
 *
 * `handle` is optional:
 * * pass `0n` (or omit it via the TypeScript optional parameter)
 *   to get a bridge-only envelope — useful immediately after
 *   loading the addon, before any [`js_open_store`] call.
 * * pass a [`BigInt`] returned by [`js_open_store`] to get a full
 *   probe (`bridge` + `evidence_store` + `crypto` + `memory_manager`
 *   + `inference_router` + `connector` subsystems, with real
 *   per-subsystem I/O). The `connector` subsystem reports the
 *   in-memory connector-instance count, authenticated-token count,
 *   and per-`SyncStatus` distribution across all registered
 *   connectors (downgrading to `Degraded` if any connector is in
 *   `Failed`).
 *
 * Returns the [`ffi::HealthStatus`] envelope serialised to JSON.
 * JS hosts get a typed object via napi's `serde_json::Value`
 * transparent passthrough; the shape is documented in
 * `crates/napi/index.d.ts`.
 */
export declare function healthCheck(handle?: bigint | undefined | null): any

/**
 * Ingest a chat / document message. Mirrors
 * [`crate::ingest_message`]. The `req` argument is a plain JS
 * object shaped like [`IngestRequest`].
 */
export declare function ingestMessage(handle: bigint, req: any): any

/** Initialise the Rust core. Mirrors [`crate::init`]. */
export declare function init(configJson: string): void

/**
 * List approved documents admitted onto the tenant memory for
 * `scopeId` along with persisted payload metadata. Mirrors
 * [`crate::list_approved_documents`].
 *
 * Returns an empty array for a forgotten / never-touched scope
 * (matching the "soft" semantic shared with
 * [`js_list_recent_syntheses`]). Orphan refs (a tenant-memory ref
 * without a persisted payload row, e.g. from legacy admission
 * paths) surface with `payloadBytes = 0`.
 *
 * # Errors
 *
 * * `InvalidArgument` if `scopeId` is not a UUID.
 */
export declare function listApprovedDocuments(handle: bigint, scopeId: string): any

/**
 * List configured connector instances. Mirrors
 * [`crate::list_connectors`]. Returns a JSON array of
 * [`ConnectorStatus`] objects.
 */
export declare function listConnectors(handle: bigint): any

/**
 * List memory records, optionally filtered. Mirrors
 * [`crate::list_memories`]. The `filter` argument is a JSON object
 * whose key set must match [`MemoryFilter`] exactly — `state` is
 * optional (`null` or omitted ⇒ no state filter) and `pinned_only`
 * is a required bool. The struct carries
 * `#[serde(deny_unknown_fields)]`, so a typo like `pinnedOnly`
 * (camelCase) or `Pinned_Only` errors out with a clear
 * `InvalidArgument` rather than silently defaulting — this catches
 * JS-side mistakes at the FFI boundary instead of letting them
 * surface as missing memory rows later in the pipeline.
 */
export declare function listMemories(handle: bigint, scopeId: string, filter: any): any

/**
 * Enumerate recent synthesis windows for `scopeId`. Mirrors
 * [`crate::list_recent_syntheses`]. Returns the rows sorted by
 * `windowEnd` descending and capped at
 * [`ffi::LIST_RECENT_SYNTHESES_CAP`].
 *
 * Returns an empty array for a scope with no recorded synthesis
 * history — including the forgotten / unknown / never-touched
 * cases. This matches the underlying FFI's "soft" semantic and
 * avoids surfacing tombstone state to the host (mirroring how
 * `list_channel_facts` etc. handle forgotten scopes).
 *
 * # Errors
 *
 * * `InvalidArgument` if `scopeId` is not a UUID.
 */
export declare function listRecentSyntheses(handle: bigint, scopeId: string): any

/**
 * Enumerate every running webhook server on `handle` with its
 * per-server counters. Mirrors [`crate::list_webhook_servers`].
 * Returns a `serde_json::Value` (`Vec<WebhookServerSummary>`) so
 * callers can destructure
 * `{ serverHandle, bindAddr, startedAt, registrationCount,
 *   dispatchOkTotal, dispatchBadRequestTotal, dispatchBadGatewayTotal }`
 * shapes without an additional `JSON.parse`.
 *
 * # JS handle representation
 *
 * `serverHandle` is serialised as a JSON `number`, not a
 * `BigInt` — consistent with the rest of the N-API `list*` family
 * (`listConnectors`, `listConnectorAuthState`, …) which all route
 * through `serde_json::to_value`. By contrast,
 * [`js_start_webhook_server`] returns the freshly-minted handle as
 * a `BigInt` (the canonical FFI representation). Hosts comparing
 * a handle taken from this list against one returned by
 * `startWebhookServer` must coerce to a common type: either widen
 * the list value via `BigInt(row.serverHandle)` or narrow the
 * start return via `Number(handle)`. Loose `==` works across the
 * `BigInt`/`Number` pair but strict `===` does NOT. Handles start
 * at `1` and increment monotonically (`u64` allocator at
 * `crates/ffi/src/webhook.rs::next_server_handle`); JavaScript
 * `Number` preserves integer precision up to `2^53 − 1`, so a
 * `number` representation is exact for any realistic substrate
 * uptime, but the `BigInt`-vs-`number` asymmetry is still a real
 * pitfall worth pinning at the call site.
 *
 * # Errors
 *
 * * `Unavailable` if `open_store(handle)` has not yet been called.
 */
export declare function listWebhookServers(handle: bigint): any

/**
 * Open the SQLCipher-backed evidence store. Mirrors
 * [`crate::open_store`]. Returns a JS `BigInt` handle the caller
 * passes back into every subsequent call.
 */
export declare function openStore(path: string, masterKeyHex: string): bigint

/** Pin a memory record. Mirrors [`crate::pin`]. */
export declare function pin(handle: bigint, id: string): void

/** Hybrid query against a scope. Mirrors [`crate::query`]. */
export declare function query(handle: bigint, req: any): any

/**
 * Drive an OAuth2 `grant_type=refresh_token` round-trip against
 * the provider's token endpoint, persist the refreshed token to
 * SQLCipher, and update the per-runtime token vault. Mirrors
 * [`crate::refresh_connector_token`]. Returns the
 * [`RefreshReport`] envelope serialised as `serde_json::Value`
 * for JS so callers can destructure `{ instanceId, refreshed,
 * expiresAt, refreshedAt }` directly.
 *
 * Failure modes:
 *
 * * `kind: "connector"` carrying the framework's `TokenRefresh`
 *   diagnostic when the provider rejects the refresh grant
 *   (refresh token revoked / expired). The host should treat
 *   this as "re-authorisation required" and prompt the user
 *   through `authenticateConnector` rather than retrying the
 *   refresh.
 * * `kind: "connector"` carrying `"no refresh_token stored …"`
 *   when the cached token has no refresh token (Slack legacy,
 *   PKCE-only public clients). Same recovery as above.
 * * `kind: "not_found"` (`kind = "connector" | "scope"`) when
 *   the instance / scope was removed during the unlocked refresh
 *   round-trip.
 * * `kind: "unavailable"` (`subsystem: "connector-http-client"`)
 *   when no real HTTP transport is linked into the build.
 */
export declare function refreshConnectorToken(handle: bigint, instanceId: string): any

/**
 * Bind `providerId` (one of the framework's recognised connector
 * slugs — `"slack"`, `"notion"`, …) to `instanceId` on the
 * running `serverHandle`. Mirrors
 * [`crate::register_webhook_dispatch`].
 *
 * Re-registering an already-bound `providerId` REPLACES the prior
 * binding (idempotent).
 *
 * # Errors
 *
 * * `Unavailable` if `open_store(handle)` has not yet been called.
 * * `InvalidArgument` if `instanceId` is not a valid UUID.
 * * `NotFound` if `serverHandle` or `instanceId` does not name a
 *   live entity.
 * * `Connector` if `providerId` is not one of the framework's
 *   recognised connector slugs.
 */
export declare function registerWebhookDispatch(handle: bigint, serverHandle: bigint, providerId: string, instanceId: string): void

/** Tear down a connector. Mirrors [`crate::remove_connector`]. */
export declare function removeConnector(handle: bigint, instanceId: string): void

/**
 * Replace the payload and metadata of an existing approved
 * document while keeping its `documentId` stable. Mirrors
 * [`crate::replace_approved_document`].
 *
 * Use this when the host wants to publish a new revision of a
 * previously-admitted document without changing the id that
 * downstream synthesis / audit consumers reference. The
 * `documentId` and `scopeId` remain identical; `label`,
 * `approver`, `payload`, `contentHashHex`, `payloadBytes`, and
 * `approvedAtMs` are refreshed. A fresh `approvedAtMs` means the
 * replaced document is treated as "recently touched" by the
 * per-dispatch LRU cap.
 *
 * Returns the serialised [`ffi::ApprovedDocumentSummary`] with
 * camelCase keys, identical in shape to
 * [`js_admit_approved_document`].
 *
 * # Errors
 *
 * * `NotFound { kind: "scope" }` if the scope has been forgotten
 *   via `forgetScope`.
 * * `NotFound { kind: "tenant_memory" }` if no tenant memory
 *   object exists for the scope (no document has ever been
 *   admitted on it). Hosts must `admitApprovedDocument` first.
 * * `NotFound { kind: "approved_document" }` if `documentId` is
 *   not currently admitted on this scope's tenant memory.
 * * `Memory` if `label` / `approver` / `payload` are empty or
 *   exceed their documented size caps (see
 *   [`crate::MAX_APPROVED_DOCUMENT_BYTES`] and
 *   [`crate::MAX_APPROVED_DOCUMENT_METADATA_BYTES`]).
 * * `InvalidArgument` if `scopeId` or `documentId` is not a UUID.
 *
 * The three-way `kind` distinction mirrors `revokeApprovedDocument`
 * so JS/TS hosts can pattern-match on `err.kind` uniformly across
 * both functions.
 */
export declare function replaceApprovedDocument(handle: bigint, scopeId: string, documentId: string, label: string, approver: string, payload: Buffer): any

/**
 * Revoke an approved document previously admitted via
 * [`js_admit_approved_document`]. Mirrors
 * [`crate::revoke_approved_document`]. Removes both the
 * tenant-memory ref and the persisted AEAD-encrypted payload row.
 *
 * # Errors
 *
 * * `NotFound` if the scope has been forgotten or no document
 *   matches `documentId`.
 * * `InvalidArgument` if `scopeId` or `documentId` is not a UUID.
 */
export declare function revokeApprovedDocument(handle: bigint, scopeId: string, documentId: string): void

/**
 * Run the per-scope memory decay sweep. Mirrors
 * [`crate::run_decay_sweep`].
 */
export declare function runDecaySweep(handle: bigint, scopeId: string): number

/**
 * Register a host-supplied OAuth2 client-secret resolver against
 * `handle`'s per-runtime [`ffi::OAuth2Client`]. Mirrors
 * [`crate::set_oauth_client_secret_resolver`].
 *
 * `resolver` is a JS function with the signature
 * `(kind: string, scopeId: string, clientId: string) =>
 * string | null | undefined`. Returning `null` / `undefined`
 * (both map to `None` on the Rust side) defers to the next
 * layer of the framework's fallback ladder. Returning `""`
 * (an empty string) is treated as an **explicit "no-secret"
 * choice** and short-circuits both the `auth_config_json`
 * fallback and any static `with_client_secret` value — the
 * substrate then omits the `client_secret` form field entirely
 * (public-client semantics). Returning a non-empty string uses
 * that secret. See the trait-level rustdoc on
 * [`ffi::OAuthClientSecretResolver`] for the full semantics and
 * [`connector_framework::OAuth2Client::client_secret_for`] for
 * the resolution ladder.
 *
 * The JS callback runs on the JS event loop (the substrate's
 * connector worker threads `await` the result via a
 * [`ThreadsafeFunction`]); implementations are free to look the
 * secret up from the OS keychain, an in-memory cache, or any
 * async source as long as the call returns synchronously to the
 * substrate's perspective.
 *
 * `timeoutMs` is an optional defense-in-depth ceiling on how long
 * the connector worker thread will block waiting for the JS
 * resolver callback to deliver its result. When exceeded the
 * adapter logs a WARN with `(kind, scopeId, clientId,
 * timeout_ms)` and returns `None` to the framework — which then
 * falls through to the `auth_config_json["client_secret"]`
 * fallback layer just as if the resolver had returned `null`.
 * This prevents a wedged JS event loop (infinite loop in user
 * code, deadlock on another JS lock, etc.) from stalling the
 * connector worker thread permanently.
 *
 * Omit `timeoutMs` (or pass `null`/`undefined`) to use the
 * adapter's default ceiling (5000 ms) — generous enough for any
 * in-memory cache / keychain-cached lookup. Pass a larger value
 * only if a slow cold-path lookup is expected at startup (e.g.
 * a keychain unlock that prompts the OS for the user's password).
 * A value of `0` is rejected as ambiguous (would always time out
 * before the JS event loop drained); pass an explicitly-large
 * value (e.g. 60_000) for "effectively unbounded" semantics.
 *
 * Calling this multiple times REPLACES the previously-registered
 * resolver. Hosts typically call this exactly once per
 * `open_store` lifecycle.
 */
export declare function setOauthClientSecretResolver(handle: bigint, resolver: (arg: [string, string, string]) => string | null, timeoutMs?: number | undefined | null): void

/**
 * Start the background sync scheduler (Phase 6).
 *
 * Spawns a dedicated OS thread that wakes every
 * `tickIntervalSecs` seconds, walks the connector instance map,
 * and dispatches [`js_sync_connector`] for every connector
 * instance whose `lastSyncedAt + syncInterval` has elapsed.
 *
 * Per-instance overrides for `syncInterval` and `maxBackoff` are
 * set via [`js_configure_sync_schedule`]; instances without an
 * override use the defaults provided here.
 *
 * # JS argument types
 *
 * All three numeric arguments are JS `number` (not `BigInt`)
 * because realistic scheduler intervals fit in `u32` and the JS
 * `Number` representation is exact for any sub-`2^53` integer.
 * N-API marshals them through the standard `u32`/`u64` adapters
 * — values larger than `Number.MAX_SAFE_INTEGER` will round-trip
 * lossily, but no realistic scheduler config approaches that
 * bound.
 *
 * # Errors
 *
 * * `Unavailable` if `open_store(handle)` has not yet been called.
 * * `InvalidArgument` if any argument is `0`, or if
 *   `defaultMaxBackoffSecs < defaultIntervalSecs`.
 * * `Connector` if a scheduler is already running on this handle
 *   (call [`js_stop_sync_scheduler`] first).
 */
export declare function startSyncScheduler(handle: bigint, defaultIntervalSecs: number, defaultMaxBackoffSecs: number, tickIntervalSecs: number): void

/**
 * Start a webhook receiver server bound to `bindAddr` (parsed as
 * a `SocketAddr` — `"127.0.0.1:9001"`, `"0.0.0.0:0"` for an
 * ephemeral port, `"[::1]:9001"` for IPv6). Mirrors
 * [`crate::start_webhook_server`]. Returns the opaque server
 * handle as a `BigInt`.
 *
 * # Errors
 *
 * * `Unavailable` if `open_store(handle)` has not yet been called.
 * * `InvalidArgument` if `bindAddr` is not a valid `host:port`
 *   string.
 * * `Connector` if the OS rejects the bind (port in use,
 *   permission denied) or the tokio runtime fails to spin up.
 */
export declare function startWebhookServer(handle: bigint, bindAddr: string): bigint

/**
 * Stop the background sync scheduler (Phase 6).
 *
 * Signals shutdown to the worker thread and synchronously joins
 * it. Idempotent — calling on a runtime with no scheduler
 * running returns `Ok(())`. In-flight `sync_connector` dispatches
 * run to completion under the substrate's three-phase locking
 * discipline.
 *
 * # Errors
 *
 * * `Unavailable` if `open_store(handle)` has not yet been called.
 */
export declare function stopSyncScheduler(handle: bigint): void

/**
 * Stop a previously-started webhook server and synchronously join
 * its runtime thread. Mirrors [`crate::stop_webhook_server`].
 *
 * Idempotent — stopping an unknown / already-stopped server
 * returns success with no work.
 *
 * # Errors
 *
 * * `Unavailable` if `open_store(handle)` has not yet been called.
 * * `InvalidArgument` if `serverHandle` cannot be represented as
 *   a u64.
 */
export declare function stopWebhookServer(handle: bigint, serverHandle: bigint): void

/**
 * Run a connector sync and ingest emitted events into the evidence
 * store. Mirrors [`crate::sync_connector`]. Returns the
 * [`SyncReport`] envelope serialised as `serde_json::Value` for JS.
 */
export declare function syncConnector(handle: bigint, instanceId: string): any

/**
 * Snapshot the scheduler's diagnostic state (Phase 6). Returns a
 * `serde_json::Value` ([`ffi::SyncSchedulerStatus`]) with
 * camelCase keys so callers can destructure
 * `{ isRunning, startedAtUnix, defaultIntervalSecs,
 *    defaultMaxBackoffSecs, tickIntervalSecs, policyOverrideCount,
 *    totalInstanceCount, lastTickAtUnix, ticksCompleted,
 *    dispatchesAttempted, dispatchesSucceeded, dispatchesFailed,
 *    dispatchesSkippedInProgress }` directly.
 *
 * `policyOverrideCount` reports how many connector instances have
 * a custom [`crate::configure_sync_schedule`] policy set;
 * `totalInstanceCount` reports how many connector instances the
 * scheduler is driving in total. The former is a strict subset of
 * the latter — a host UI that wants "how many connectors is the
 * scheduler syncing" should read `totalInstanceCount`.
 *
 * A stopped scheduler reports `isRunning=false` and zero
 * counters; this is NOT an error. The host can call
 * [`js_start_sync_scheduler`] to begin dispatching.
 *
 * # Errors
 *
 * * `Unavailable` if `open_store(handle)` has not yet been called.
 */
export declare function syncSchedulerStatus(handle: bigint): any

/**
 * Look up the lifecycle state of a synthesis window. Mirrors
 * [`crate::synthesis_status`].
 *
 * Returns the serialised [`ffi::SynthesisStatusRecord`] with
 * camelCase keys:
 * `{ synthesisId, scopeId, tier, status, windowStartUnix,
 *    windowEndUnix, objectId }`.
 *
 * # Errors
 *
 * * `NotFound` if no window matches `synthesisId`.
 * * `InvalidArgument` if `synthesisId` is not a UUID.
 */
export declare function synthesisStatus(handle: bigint, synthesisId: string): any

/**
 * Dispatch a server-side synthesis run for `scopeId` at the
 * requested `tier`. Mirrors [`crate::trigger_server_synthesis`].
 * `tier` is `"domain"` or `"tenant"` (matches
 * [`ffi::SynthesisTierKind`]'s serde rename rules).
 *
 * Returns the UUID string of the newly-opened synthesis window.
 * Callers can poll [`js_synthesis_status`] with the same value
 * to observe state transitions.
 *
 * # Errors
 *
 * * `Unavailable` if no engine is configured or the runtime has
 *   been forgotten for this scope.
 * * `NotFound` if the scope has no domain / tenant memory
 *   object registered.
 * * `Synthesis` for engine, validation, or persistence
 *   failures.
 * * `InvalidArgument` if `scopeId` is not a UUID or `tier` is
 *   not one of the documented values.
 */
export declare function triggerServerSynthesis(handle: bigint, scopeId: string, tier: string): string

/**
 * Trigger synthesis for a scope. Mirrors
 * [`crate::trigger_synthesis`]. `trigger` is one of
 * `"ManualUserAction"` / `"BackgroundIdle"` / `"EvidenceThreshold"` /
 * `"ConnectorSyncCompleted"` (matching the
 * [`SynthesisTrigger`] enum's serde-rename rules).
 */
export declare function triggerSynthesis(handle: bigint, scopeId: string, trigger: string): string

/** Lift a pin. Mirrors [`crate::unpin`]. */
export declare function unpin(handle: bigint, id: string): void

/**
 * Drop the binding for `(serverHandle, providerId)`. Mirrors
 * [`crate::unregister_webhook_dispatch`]. Idempotent.
 *
 * # Errors
 *
 * * `Unavailable` if `open_store(handle)` has not yet been called.
 * * `NotFound` if `serverHandle` does not name a running server.
 */
export declare function unregisterWebhookDispatch(handle: bigint, serverHandle: bigint, providerId: string): void
